-- Seed 499 items from ingredientes.xlsx
INSERT INTO items_catalogo (id, nombre, categoria, unidad) VALUES
('ITEM-753992d6', '1800 SILVER', 'BOTELLAS', 'Und'),
('ITEM-a6304114', 'ACEITE DE GIRASOL', 'Insumos cocina', 'Ml'),
('ITEM-775bd179', 'ACEITE DE TRUFA', 'Insumos cocina', 'Ml'),
('ITEM-49f3da06', 'AGUA CRISTAL 600 ML', 'BEBIDAS', 'Und'),
('ITEM-d27a19df', 'AGUA CRISTAL CON GAS', 'Producción BAR', 'Und'),
('ITEM-729ee17b', 'AJI DULCE', 'Insumos cocina', 'Gr'),
('ITEM-273e2f2d', 'AJI HABANERO', 'PRODUCCION COCINA', 'Gr'),
('ITEM-841eb819', 'AJO EN POLVO', 'Insumos cocina', 'Gr'),
('ITEM-e525ca6d', 'AJONJOLY', 'PRODUCCION COCINA', 'Gr'),
('ITEM-d2a6ebd4', 'ALBAHACA', 'Insumos cocina', 'Gr'),
('ITEM-e398afbe', 'ALMENDRAS', 'PRODUCCION COCINA', 'Gr'),
('ITEM-0d2b1b1b', 'ANCHOAS', 'Insumos cocina', 'Gr'),
('ITEM-2d4b4ab2', 'ANIVERSARIO 750 ML', 'RON', 'Und'),
('ITEM-14f618f8', 'ARRACHERA', 'Insumos cocina', 'Gr'),
('ITEM-34484346', 'ARVEJA', 'Insumos cocina', 'Gr'),
('ITEM-86638b81', 'ATUN', 'Insumos cocina', 'Und'),
('ITEM-fd2eafc2', 'AZUCAR MICRO', 'PRODUCCION COCINA', 'Gr'),
('ITEM-e0caf48d', 'AZUCAR MORENA', 'PRODUCCION COCINA', 'Gr'),
('ITEM-ee4a2076', 'Aceite Vegetal', 'PRODUCCION COCINA', 'ml'),
('ITEM-0dd367c8', 'Aceite de oliva', 'Insumos cocina', 'Ml'),
('ITEM-d4bb5d31', 'Aceite de olivo', 'Producción BAR', 'Und'),
('ITEM-31d81c0b', 'Aceitunas', 'Producción BAR', 'Gr'),
('ITEM-edbce914', 'Agua', 'PRODUCCION COCINA', 'Ml'),
('ITEM-e8b956f2', 'Agua Cristal 300ml', 'BEBIDAS', 'Und'),
('ITEM-d06139d3', 'Agua Cristal 600ml', 'BEBIDAS', 'Und'),
('ITEM-8d292b4c', 'Agua Hatsu', 'BEBIDAS', 'Und'),
('ITEM-d99770a1', 'Agua Manantial 500ml', 'BEBIDAS', 'Unidad'),
('ITEM-90f5c509', 'Agua Tonica 1976 India', 'BEBIDAS', 'Unidad'),
('ITEM-c619cabb', 'Agua Tonica 1976 Ocean', 'BEBIDAS', 'Und'),
('ITEM-f446f698', 'Agua Tonica 1976 Pink', 'BEBIDAS', 'Unidad'),
('ITEM-a93b98c3', 'Agua Tonica Bretaña 2.5L', 'BEBIDAS', 'Unidad'),
('ITEM-5ec6740e', 'Agua Tonica Canada Dry 300ml', 'BEBIDAS', 'Unidad'),
('ITEM-844f1a93', 'Agua Tonica Ocean', 'BEBIDAS', 'Und'),
('ITEM-0fdf43fc', 'Agua con Gas Cristal', 'BEBIDAS', 'Und'),
('ITEM-41e36830', 'Aguardiente Amarillo 750ml', 'BOTELLAS', 'Unidad'),
('ITEM-2448b4c2', 'Aguardiente Antioqueño Azul 750ml', 'BOTELLAS', 'Unidad'),
('ITEM-a0e089b2', 'Aguardiente Antioqueño Real 750ml', 'BOTELLAS', 'Unidad'),
('ITEM-48f8b852', 'Aguardiente Antioqueño Rojo 750ml', 'BOTELLAS', 'Unidad'),
('ITEM-07288830', 'Aguardiente Antioqueño Verde 750ml', 'BOTELLAS', 'Unidad'),
('ITEM-83b0089f', 'Ahuyama', 'PRODUCCION COCINA', 'Gr'),
('ITEM-093d5c6a', 'Ajii jalapenos', 'Insumos cocina', 'Gr'),
('ITEM-773f25d9', 'Ajo', 'Insumos cocina', 'Gr'),
('ITEM-06dd251a', 'Ají chile', 'Producción BAR', 'Kg'),
('ITEM-169dcf57', 'Alas de Pollo', 'PRODUCCION COCINA', 'Kg'),
('ITEM-10adec11', 'Amargo de angostura', 'Producción BAR', 'Ml'),
('ITEM-6021f869', 'Anis estrella', 'Insumos cocina', 'Gr'),
('ITEM-6ad222a9', 'Aperol 750ml', 'LICORES', 'Unidad'),
('ITEM-4625f700', 'Apio', 'PRODUCCION COCINA', 'Gr'),
('ITEM-cd762ef8', 'Arroz', 'PRODUCCION COCINA', 'Gr'),
('ITEM-194397ad', 'Avena Tonic', 'PRODUCCION COCINA', 'Gr'),
('ITEM-015598e2', 'Azucar', 'Producción BAR', 'Gr'),
('ITEM-b84f23b5', 'Azucar Aro', 'Insumos cocina', 'Gr'),
('ITEM-9eb71ab7', 'BATATA', 'PRODUCCION COCINA', 'Gr'),
('ITEM-7a52822d', 'BULLDOG', 'VODKA / GIN', 'Unidad'),
('ITEM-d304f11f', 'BURRATA', 'PRODUCCION COCINA', 'Unidad'),
('ITEM-471af717', 'Baileys 700ml', 'LICORES', 'Unidad'),
('ITEM-4e919ac3', 'Bara de canela', 'Producción BAR', 'Und'),
('ITEM-9cf940b0', 'Berenjena', 'Insumos cocina', 'Gr'),
('ITEM-6d1571f1', 'Bermut Martini Bianco 750ml', 'LICORES', 'Unidad'),
('ITEM-9f83b4c9', 'Bermut Martini Rosso 750ml', 'LICORES', 'Unidad'),
('ITEM-08b29546', 'Bicarbonato Aro', 'Insumos cocina', 'Gr'),
('ITEM-ffbe6574', 'Bofe', 'PRODUCCION COCINA', 'Gr'),
('ITEM-acbdaaf6', 'Brandy Domecq 750ml', 'LICORES', 'Unidad'),
('ITEM-93ed3fc0', 'Brandy Gran Duque De Alba 750-ml', 'LICORES', 'Und'),
('ITEM-a95d015e', 'Brocheta de pepino', 'Producción BAR', 'Und'),
('ITEM-40ca15e2', 'Buchanan 12 - 750ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-6c966b7f', 'Buchanan 18 - 750ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-444b7112', 'Bulleit Bourbon 750ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-7ff6961f', 'Bulleit Rye 750ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-e01554d1', 'CALABAZA', 'PRODUCCION COCINA', 'Gr'),
('ITEM-821bfe20', 'CAMARON', 'Insumos cocina', 'Gr'),
('ITEM-13f0a23d', 'CANELA  EN ASTILLAS', 'Insumos cocina', 'Gr'),
('ITEM-17404224', 'CARAMBOLO', 'Insumos cocina', 'Gr'),
('ITEM-5798ce71', 'CARIMAÑOLAS DE CARNE', 'PRODUCCION COCINA', 'Und'),
('ITEM-47031d6d', 'CARNE BISTECK', 'PLATOS PRINCIPALES', 'Kg'),
('ITEM-ebbac90b', 'CARNE MOLIDA', 'Insumos cocina', 'Kg'),
('ITEM-42a1751f', 'CEREAL', 'Insumos cocina', 'Und'),
('ITEM-d8565c75', 'CHIA', 'Insumos cocina', 'Gr'),
('ITEM-dc9a9ac4', 'CHICHARRONES por 200gr', 'PRODUCCION COCINA', 'Unidad'),
('ITEM-004be620', 'CHILE CHIPOTLE', 'Insumos cocina', 'Gr'),
('ITEM-85661f37', 'CHULETA', 'PRODUCCION COCINA', 'Kg'),
('ITEM-4e9fceb1', 'CLAMATO 64 Oz', 'Producción BAR', 'Oz'),
('ITEM-988c50b4', 'CLAVOS DE OLOR', 'Insumos cocina', 'Gr'),
('ITEM-ab231f31', 'COBERTURA DE CHOCOLATE BLANCO', 'Insumos cocina', 'Gr'),
('ITEM-941909b2', 'COCADAS TRADICIONALES', 'PRODUCCION COCINA', 'Und'),
('ITEM-6381412a', 'CONTENEDOR DELI LITRO', 'PRODUCCION COCINA', 'Und'),
('ITEM-6eabe631', 'CREMA DE AVELLANA', 'Otros', 'Gr'),
('ITEM-933fbac8', 'CUBIERTOS DESECHABLES', 'PRODUCCION COCINA', 'Und'),
('ITEM-c4218985', 'Cabeza de pescado', 'Insumos cocina', 'Gr'),
('ITEM-a0e2171b', 'Cafe Sello Rojo', 'BEBIDA CALIENTES - HOT SOFT DRINKS', 'Gr'),
('ITEM-b871e863', 'Cafe juan valdez capsula x 8', 'Producción BAR', 'Und'),
('ITEM-07117fe4', 'Café', 'Producción BAR', 'Gr'),
('ITEM-5618830e', 'Café Sello Rojo', 'PRODUCCION COCINA', 'Gr'),
('ITEM-d1f442e5', 'Caja de pizza', 'PIZZAS Y TACOS', 'Und'),
('ITEM-eb616caf', 'Calamar', 'Insumos cocina', 'Gr'),
('ITEM-f0e91b9c', 'Campari 750ml', 'LICORES', 'Unidad'),
('ITEM-e17da215', 'Canela', 'Producción BAR', 'Und'),
('ITEM-f79e11f0', 'Cebolla Morada', 'Insumos cocina', 'Gr'),
('ITEM-11c52c3c', 'Cebolla blanca', 'Insumos cocina', 'Gr'),
('ITEM-12bdbbe4', 'Cerdo Barriguero', 'PRODUCCION COCINA', 'Gr'),
('ITEM-9f8b70e2', 'Cereza', 'Producción BAR', 'Unidad'),
('ITEM-c8080a64', 'Cereza marrasquino', 'Producción BAR', 'Gr'),
('ITEM-97d7a58e', 'Cerveza Aguila Light', 'CERVEZAS', 'Unidad'),
('ITEM-74f74fcd', 'Cerveza Aguila Original', 'CERVEZAS', 'Unidad'),
('ITEM-228df5ee', 'Cerveza Corona', 'CERVEZAS', 'Unidad'),
('ITEM-4d114dad', 'Cerveza Coronita', 'CERVEZAS', 'Unidad'),
('ITEM-693d81cd', 'Cerveza Costeñita', 'CERVEZAS', 'Unidad'),
('ITEM-4256bc07', 'Cerveza Heineken', 'CERVEZAS', 'Unidad'),
('ITEM-9b7c07ab', 'Cerveza Stella Artois', 'CERVEZAS', 'Unidad'),
('ITEM-128e15df', 'Chile Guajillo', 'Insumos cocina', 'Gr'),
('ITEM-dd217000', 'Chile Jalapeno', 'Insumos cocina', 'Gr'),
('ITEM-d09a211f', 'Chivas Regal 12 - 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-cd399527', 'Chivas Regal 18 - 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-63f8ed62', 'Cilantro', 'PRODUCCION COCINA', 'Gr'),
('ITEM-24e9b4a5', 'Clara de huevo', 'Producción BAR', 'Und'),
('ITEM-4de47fa1', 'Clavo de olor', 'Producción BAR', 'Gr'),
('ITEM-95b63315', 'Club Colombia', 'CERVEZAS', 'Unidad'),
('ITEM-016ee68f', 'Coca Cola Original 3L', 'BEBIDAS', 'Unidad'),
('ITEM-600da00a', 'Coca Cola Original Botella 400ml', 'BEBIDAS', 'Unidad'),
('ITEM-dd108f1d', 'Coca Cola Zero 2.5L', 'BEBIDAS', 'Unidad'),
('ITEM-f6ec7289', 'Coca Cola Zero Botella 400ml', 'BEBIDAS', 'Unidad'),
('ITEM-c56c0c51', 'Coco Rallao', 'Producción BAR', 'Gr'),
('ITEM-37106cc4', 'Coco deshidratado', 'Producción BAR', 'Gr'),
('ITEM-1ed76d35', 'Cocoa', 'Insumos cocina', 'Gr'),
('ITEM-d1eff14e', 'Cocoa en polvo', 'Producción BAR', 'Und'),
('ITEM-2a217e6e', 'Codillo', 'PRODUCCION COCINA', 'Gr'),
('ITEM-6fe3130e', 'Cognac Hennessy 700-ml', 'BOTELLAS', 'Und'),
('ITEM-b8e05797', 'Cognac grand marnier 750-ml', 'BOTELLAS', 'Und'),
('ITEM-9944108d', 'Comino Badia', 'Insumos cocina', 'Gr'),
('ITEM-561d028e', 'Confitado de corozo', 'PRODUCCION COCINA', 'Gr'),
('ITEM-50061bfa', 'Corozo', 'Producción BAR', 'Kg'),
('ITEM-c9184309', 'Corozo x ml', 'Jugos', 'Ml'),
('ITEM-0887bb4f', 'Crema de coco', 'Producción BAR', 'Ml'),
('ITEM-d41b391e', 'Crema de leche', 'Insumos cocina', 'ml'),
('ITEM-59caab0f', 'DICTADOR 12 AÑOS 750 ML', 'RON', 'Und'),
('ITEM-755455cb', 'DICTADOR 20 AÑOS 750 ML', 'RON', 'Und'),
('ITEM-4708e837', 'DIPLOMATICO 700 ML', 'RON', 'Und'),
('ITEM-990163d6', 'DON SIMON VINO BLANCO', 'VINOS / ESPUMOSOS', 'Und'),
('ITEM-a33c0272', 'Dash orange bitter', 'Producción BAR', 'Ml'),
('ITEM-265e4e7d', 'Don Julio 1942 - 750ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-ec0867aa', 'Don Julio 70 - 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-5fe41214', 'Don Julio Anejo 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-7c9b8db3', 'Don Julio Blanco 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-a5d13813', 'Don Julio Reposado 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-c2688dda', 'ESPARRAGO', 'Insumos cocina', 'Gr'),
('ITEM-eeb1c0d2', 'Electrolit 625ml', 'BEBIDAS', 'Unidad'),
('ITEM-d1a70e32', 'Esencia Vainilla Levapan', 'PRODUCCION COCINA', 'ml'),
('ITEM-f99cb8ac', 'Espinacas', 'Insumos cocina', 'Gr'),
('ITEM-ed4f51cc', 'Espumoso Baron Rotberg 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-19b4afd5', 'Espumoso Chandon Brut', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-0979b616', 'Espumoso Chandon Brut 187ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-ac304980', 'Espumoso Chandon Rose 187ml', 'VINOS / ESPUMOSOS', 'Und'),
('ITEM-86dd19cf', 'Espumoso Chandon Rose 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-25190040', 'Espumoso Moelia Brut', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-f219e048', 'Espumoso Moelia Rose', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-9a3b32a4', 'FEVER TREE  TONICA 200 ML', 'BEBIDAS', 'Und'),
('ITEM-fc482ceb', 'FRANGELICO 750 ML', 'LICORES', 'Und'),
('ITEM-502481fc', 'FRIJOL ROJO', 'Insumos cocina', 'Gr'),
('ITEM-49176173', 'FRUTOS ROJOS CONGELADOS', 'Insumos cocina', 'Kg'),
('ITEM-ab42717c', 'Filete de Tilapia', 'Insumos cocina', 'Gr'),
('ITEM-7ffd049b', 'Flor de Cana 4 Anos', 'RON', 'Und'),
('ITEM-1ac98632', 'Fresa', 'PRODUCCION COCINA', 'Gr'),
('ITEM-ef64312e', 'Fruta corozo', 'PRODUCCION COCINA', 'Gr'),
('ITEM-02913cbc', 'Fusion de jalapeño', 'Producción BAR', 'Ml'),
('ITEM-e99cd254', 'GALLETAS DUCALES (TACO)', 'Insumos cocina', 'Und'),
('ITEM-f9ae44c1', 'GARBANZOS', 'Insumos cocina', 'Gr'),
('ITEM-f7670abe', 'GELATINA SIN SABOR', 'POSTRES', 'Gr'),
('ITEM-18528643', 'GENJIBRE', 'Insumos cocina', 'Gr'),
('ITEM-4d88a064', 'GUACAMOLE', 'Insumos cocina', 'Gr'),
('ITEM-cd0a65ef', 'GUATILA', 'Insumos cocina', 'Gr'),
('ITEM-aecda691', 'Ginebra Beaffetar Pink 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-e4c00466', 'Ginebra Beaffeter 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-af15c531', 'Ginebra Bombay Sapphire 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-2ce0c0c9', 'Ginebra Gordons 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-dd489e02', 'Ginebra Hendricks 750ml', 'VODKA / GIN', 'Unidad'),
('ITEM-376e72b1', 'Ginebra Monkey 47 - 500ml', 'VODKA / GIN', 'Unidad'),
('ITEM-b03906b3', 'Ginebra Tanqueray Dry 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-1c8005b4', 'Ginebra Tanqueray Ten', 'VODKA / GIN', 'Unidad'),
('ITEM-130528ff', 'Ginger Beer', 'BEBIDAS', 'Und'),
('ITEM-4370ce8a', 'Ginger Canada Dry 300ml', 'BEBIDAS', 'Und'),
('ITEM-0b0909d3', 'Grey Goose 700ml OZ', 'Shots', 'Unidad'),
('ITEM-a60674ff', 'HUESO DE RES', 'Insumos cocina', 'Kg'),
('ITEM-e89b3a76', 'Hamburguesa Angus', 'PRODUCCION COCINA', 'Und'),
('ITEM-4c00ca60', 'Harina de maiz', 'PRODUCCION COCINA', 'Gr'),
('ITEM-a01cbcb6', 'Havana 3 años  750 ML', 'RON', 'Und'),
('ITEM-50bd8a6b', 'Herbabuena gr', 'Producción BAR', 'Gr'),
('ITEM-10bd16fb', 'Hielo', 'Producción BAR', 'Gr'),
('ITEM-77267b3d', 'Hierba buena', 'Producción BAR', 'Gr'),
('ITEM-f4faee8e', 'Hojas de hierbabuena', 'Producción BAR', 'Und'),
('ITEM-439fa3b6', 'Hueso', 'PRODUCCION COCINA', 'Gr'),
('ITEM-6570200d', 'Huevos', 'Insumos cocina', 'Und'),
('ITEM-b79f73ce', 'Infusion de chile jalapeño', 'Producción BAR', 'Ml'),
('ITEM-8efc8185', 'Insta crean x100', 'Producción BAR', 'Und'),
('ITEM-1d74d57f', 'JAMON DE PAVO', 'Insumos cocina', 'Gr'),
('ITEM-5f747fdb', 'JUGO DE NARANJA', 'PRODUCCION COCINA', 'Ml'),
('ITEM-f50fec59', 'Jack Daniels #7 - 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-225c812d', 'Jagermeister 700ml', 'BOTELLAS', 'Und'),
('ITEM-76720141', 'Jameson 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-7f869e37', 'Jarabe de canela', 'Producción BAR', 'Ml'),
('ITEM-41ba32bb', 'Jarabe de lychee', 'Producción BAR', 'Oz'),
('ITEM-1f669248', 'Jarabe de pepino', 'Producción BAR', 'Oz'),
('ITEM-c0f50707', 'Jarabe de romero', 'Producción BAR', 'Oz'),
('ITEM-d374f1a4', 'Jarabe natural', 'Producción BAR', 'Ml'),
('ITEM-07b508e0', 'Jengibre', 'PRODUCCION COCINA', 'Gr'),
('ITEM-c98bbef8', 'Johnnie Walker Black Label 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-d2b14d52', 'Johnnie Walker Blue Label 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-9c64b037', 'Johnnie Walker Red Label 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-e7761d84', 'Jose Cuervo Blanco 750ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-a931aab9', 'Jose Cuervo Reposado 750ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-09729abb', 'Jugo de Tomate', 'Producción BAR', 'Ml'),
('ITEM-55af876e', 'Jugo de limon', 'Producción BAR', 'Ml'),
('ITEM-a2cbe2bf', 'Jugo de maggie', 'Producción BAR', 'Und'),
('ITEM-8f161e73', 'Jugo de maracuya', 'Producción BAR', 'Ml'),
('ITEM-cf2a1d15', 'Jugo de pepino', 'Producción BAR', 'Ml'),
('ITEM-58db8baf', 'Jugo de piña', 'Producción BAR', 'Ml'),
('ITEM-7dd97c37', 'Jugo de sandia', 'Producción BAR', 'Ml'),
('ITEM-8e584a6b', 'Kola Roman Botella 400ml', 'BEBIDAS', 'Unidad'),
('ITEM-ccc92eb1', 'LANGOSTA', 'Insumos cocina', 'Gr'),
('ITEM-075df58e', 'LANGOSTINOS', 'Insumos cocina', 'Gr'),
('ITEM-811fd5e8', 'LAURENT PERRIER BRUT', 'VINOS / ESPUMOSOS', 'Und'),
('ITEM-523fb3b0', 'LECHE DE ALMENDRAS', 'Insumos cocina', 'Ml'),
('ITEM-e6b7b9ec', 'LECHE DE COCO', 'Insumos cocina', 'Ml'),
('ITEM-2436fa87', 'LECHE DE SOYA', 'Insumos cocina', 'Ml'),
('ITEM-343b184f', 'LECHUGA BATABIA', 'Insumos cocina', 'Kg'),
('ITEM-6e50fb8f', 'LECHUGA CRESPA MORADA', 'Insumos cocina', 'Gr'),
('ITEM-a439ded0', 'LECHUGA ROMANA', 'Insumos cocina', 'Gr'),
('ITEM-af6698a6', 'LENTEJAS', 'Insumos cocina', 'Gr'),
('ITEM-c7113ab8', 'LICOR DE CAFÉ 750 ML', 'LICORES', 'Und'),
('ITEM-b2397403', 'LOMO FINO', 'Insumos cocina', 'Gr'),
('ITEM-988b51d7', 'Leche condensada', 'Producción BAR', 'Gr'),
('ITEM-5d20c2a7', 'Leche deslactosada', 'PRODUCCION COCINA', 'ml'),
('ITEM-089ca4f6', 'Leche entera', 'Producción BAR', 'Ml'),
('ITEM-fc3f6c35', 'Lechuga Crespa Verde', 'Insumos cocina', 'Gr'),
('ITEM-9926ae90', 'Licor 43 - 750ml', 'LICORES', 'Unidad'),
('ITEM-69b76917', 'Licor Amareto Disaronno 750ml', 'LICORES', 'Unidad'),
('ITEM-4e7624d7', 'Licor Cointreau 700ml', 'LICORES', 'Unidad'),
('ITEM-ee34edfd', 'Licor Triple Sec 750ml', 'LICORES', 'Unidad'),
('ITEM-d70d8350', 'Licor Triple Sec Blue 750ml', 'LICORES', 'Unidad'),
('ITEM-01a5480f', 'Limon', 'Insumos cocina', 'Gr'),
('ITEM-1763fa48', 'Limon B', 'Producción BAR', 'Gr'),
('ITEM-d679d00e', 'Limon deshidratado', 'Producción BAR', 'Und'),
('ITEM-749026f9', 'Lonchita amarillo', 'PRODUCCION COCINA', 'Und'),
('ITEM-013fe2f9', 'Lychee Fruta Lata', 'Producción BAR', 'Gr'),
('ITEM-b9f6e984', 'MAGGI', 'PRODUCCION COCINA', 'Und'),
('ITEM-59858797', 'MAIZ PIRA', 'PRODUCCION COCINA', 'Gr'),
('ITEM-35b8cf53', 'MANTEQUILLA PORCION', 'PRODUCCION COCINA', 'Und'),
('ITEM-42f7b876', 'MASA DE CERDO', 'Insumos cocina', 'Kg'),
('ITEM-d238644f', 'MASA DE MAIZ AMARRILLO', 'Insumos cocina', 'Gr'),
('ITEM-6241f7a6', 'MASA DE MAIZ BLANCO', 'Insumos cocina', 'Gr'),
('ITEM-9da97b31', 'MIEL', 'Insumos cocina', 'Ml'),
('ITEM-05d10623', 'MIEL DE MAPLE', 'PRODUCCION COCINA', 'Ml'),
('ITEM-9fe75de7', 'MONDONGO', 'Insumos cocina', 'Gr'),
('ITEM-a26b8235', 'MUGA RIOJA VINO ROSSE', 'BOTELLAS', 'Und'),
('ITEM-8b63b839', 'MURILLO', 'Insumos cocina', 'Gr'),
('ITEM-26a29c63', 'Macallan 12  750-ml', 'BOTELLAS', 'Und'),
('ITEM-2cf39145', 'Maestro Dobel 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-59a24e75', 'Maizena', 'PRODUCCION COCINA', 'Gr'),
('ITEM-2679ec29', 'Mantequilla', 'PRODUCCION COCINA', 'Gr'),
('ITEM-43225d12', 'Mar de Frades', 'VINOS / ESPUMOSOS', 'Und'),
('ITEM-3157152f', 'Maracuya B', 'Producción BAR', 'Gr'),
('ITEM-7e0bf47a', 'Martini Bitters 1000ml', 'LICORES', 'Unidad'),
('ITEM-07fc8458', 'Mayonesa Fruco', 'PRODUCCION COCINA', 'Gr'),
('ITEM-3a2cf274', 'Melon', 'Insumos cocina', 'Gr'),
('ITEM-b8d4891b', 'Menta', 'Producción BAR', 'Gr'),
('ITEM-90f646e7', 'Mezcal 400 Conejos 750ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-89634fe0', 'Mezcal Ojo de Tigre 750ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-92df3973', 'Mezcal Union 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-196867e9', 'Moet Chandon Brut 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-3cf6a59e', 'Moet Chandon Ice 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-853d190f', 'Mojarra roja', 'PRODUCCION COCINA', 'Und'),
('ITEM-3c760afa', 'Monkey Shoulder 700ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-49fad65a', 'Mostaza', 'PRODUCCION COCINA', 'Gr'),
('ITEM-091808fc', 'NARANJA', 'Insumos cocina', 'Gr'),
('ITEM-c1ac5085', 'NUEZ DEL BRASIL', 'Insumos cocina', 'Gr'),
('ITEM-11eb92cd', 'NUEZ MOSCADA', 'Insumos cocina', 'Und'),
('ITEM-ac631d87', 'Naranja deshidratada', 'Producción BAR', 'Und'),
('ITEM-ff3f410f', 'Naranjas Frutas', 'Producción BAR', 'Gr'),
('ITEM-0a9424fd', 'OLD PARR 18 750ML', 'WHISKY / BOURBON', 'Und'),
('ITEM-53d82494', 'OLMECA PLATA 700ML', 'BOTELLAS', 'Unidad'),
('ITEM-292cf7b1', 'Old Parr 12 - 750ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-16f419b3', 'PALITOS BURGUER', 'PRODUCCION COCINA', 'Und'),
('ITEM-6e418c3b', 'PAN ARTESANO BIMBO', 'Insumos cocina', 'Unidad'),
('ITEM-74efaf38', 'PAN BAGUETTE', 'Insumos cocina', 'Und'),
('ITEM-b0ae8979', 'PAN MASA MADRE', 'Insumos cocina', 'Unidad'),
('ITEM-5cf66634', 'PAN MOGOLLA', 'Insumos cocina', 'Und'),
('ITEM-2d48f0e5', 'PANELA', 'Producción BAR', 'Und'),
('ITEM-4336f0f3', 'PAPAS EN CASCOS', 'Insumos cocina', 'Gr'),
('ITEM-2d6128bc', 'PAPAYA', 'Insumos cocina', 'Gr'),
('ITEM-bd2e83aa', 'PARGO ROJO', 'FULL YATE MENU', 'Und'),
('ITEM-bdda56c4', 'PATRON', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-14bed6bc', 'PATRON AÑEJO BT', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-b2493483', 'PATRON REPOSADO BT', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-8c1ad6ad', 'PESCADO PERSONAL', 'PRODUCCION COCINA', 'Kg'),
('ITEM-ce313ee5', 'PIMENTON AMARILLO', 'Insumos cocina', 'Gr'),
('ITEM-169319d4', 'PISCO VIÑA DE ORO 750 ML', 'BOTELLAS', 'Und'),
('ITEM-7611fc5e', 'PULPA MANDARINA', 'Producción BAR', 'Und'),
('ITEM-70a3bd2b', 'PURE DE TRUFA', 'Insumos cocina', 'Gr'),
('ITEM-35978645', 'Pan hamburguesa', 'PLATOS PRINCIPALES', 'Und'),
('ITEM-c3bc15b3', 'Pan tajado', 'Insumos cocina', 'Unidad'),
('ITEM-a454ccfe', 'Panela D1', 'Insumos cocina', 'Und'),
('ITEM-0ac6cd34', 'Papa', 'Insumos cocina', 'Gr'),
('ITEM-57ff8051', 'Paprika Badia', 'Insumos cocina', 'Gr'),
('ITEM-0ad6d405', 'Pasta Penne', 'PRODUCCION COCINA', 'Gr'),
('ITEM-adbb4790', 'Patilla', 'Insumos cocina', 'Gr'),
('ITEM-90ef1a44', 'Patron Cristalino 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-9afa4a54', 'Pegucha', 'PRODUCCION COCINA', 'Gr'),
('ITEM-6cd357a6', 'Pepino', 'Producción BAR', 'Gr'),
('ITEM-37d3bf9a', 'Pepino Cohombro', 'Insumos cocina', 'Gr'),
('ITEM-defad677', 'Pimenton rojo', 'Insumos cocina', 'Gr'),
('ITEM-0bd09b7b', 'Pimenton verde', 'Insumos cocina', 'Gr'),
('ITEM-d67ab5ea', 'Pimienta Badia', 'Insumos cocina', 'Gr'),
('ITEM-cad77c7d', 'Pina', 'Insumos cocina', 'Gr'),
('ITEM-a25f33d4', 'Piña', 'Producción BAR', 'Und'),
('ITEM-74d57d38', 'Piña deshidratada', 'Producción BAR', 'Und'),
('ITEM-4f190778', 'Pollo Contra Muslo', 'PRODUCCION COCINA', 'Kg'),
('ITEM-0b54c82f', 'Ponche de frutas', 'Producción BAR', 'Ml'),
('ITEM-c4e62595', 'Pulpa de fresa', 'Producción BAR', 'Und'),
('ITEM-1ea27871', 'Pulpa de lulo', 'Producción BAR', 'Und'),
('ITEM-4aaf2b8e', 'Pulpa de mango', 'Producción BAR', 'Und'),
('ITEM-47c649f6', 'Pulpa de mora', 'Producción BAR', 'Und'),
('ITEM-5f96bb15', 'Pulpa lulo', 'PRODUCCION COCINA', 'Und'),
('ITEM-ffffa37c', 'Pulpa piña', 'Producción BAR', 'Und'),
('ITEM-ee90c453', 'Punta de anca', 'PRODUCCION COCINA', 'Gr'),
('ITEM-a243825b', 'QUESO AZUL', 'PLATOS PRINCIPALES', 'Gr'),
('ITEM-ffa7aa56', 'QUESO BRIE', 'Insumos cocina', 'Gr'),
('ITEM-c397aa89', 'QUESO CABRA', 'Insumos cocina', 'Gr'),
('ITEM-ae3e9ca5', 'QUESO CHEDDAR', 'Insumos cocina', 'Gr'),
('ITEM-46787302', 'QUESO GOUDA', 'Insumos cocina', 'Gr'),
('ITEM-bce91644', 'QUESO MOZARRELA BLOQUE', 'Insumos cocina', 'Gr'),
('ITEM-f4180982', 'Quatro Botella 400ml', 'BEBIDAS', 'Unidad'),
('ITEM-73c554be', 'Queso Costeño', 'PRODUCCION COCINA', 'Gr'),
('ITEM-7a650874', 'Queso Mozarella Tajado', 'Insumos cocina', 'Gr'),
('ITEM-ac2a9efb', 'Queso parmesano bloque', 'Insumos cocina', 'Gr'),
('ITEM-309578e0', 'REMOLACHA', 'Insumos cocina', 'Gr'),
('ITEM-2890f8d7', 'Rama de mente', 'Producción BAR', 'Und'),
('ITEM-c920efb2', 'Rama de romero', 'Producción BAR', 'Und'),
('ITEM-7f05e929', 'Red Bull 250ml', 'BEBIDAS', 'Unidad'),
('ITEM-70e007fc', 'Remy Martin 700ml', 'BOTELLAS', 'Unidad'),
('ITEM-567ec122', 'Rodaja de chile', 'Producción BAR', 'Und'),
('ITEM-15fa6725', 'Romero', 'Producción BAR', 'Kg'),
('ITEM-289f260d', 'Ron Bacardi Añejo 700ml', 'RON', 'Unidad'),
('ITEM-39c1f5e1', 'Ron Bacardi Blanco 700ml', 'RON', 'Unidad'),
('ITEM-67d92f83', 'Ron Cachaza 51 - 965-ml', 'RON', 'Und'),
('ITEM-a36529ac', 'Ron Havana 7 año - 700ml', 'RON', 'Unidad'),
('ITEM-8ff3403d', 'Ron La Hechicera 700ml', 'RON', 'Unidad'),
('ITEM-7a19c10f', 'Ron Viejo de Caldas Blanco 750ml', 'RON', 'Unidad'),
('ITEM-f230afda', 'Ron Viejo de Caldas Tradicional 750ml', 'RON', 'Unidad'),
('ITEM-ba25d977', 'Rugula', 'PRODUCCION COCINA', 'Gr'),
('ITEM-906bade4', 'SALCHICHAS', 'Insumos cocina', 'Und'),
('ITEM-ac83fd2a', 'SALCHICHON', 'Insumos cocina', 'Gr'),
('ITEM-dea8e4bf', 'SALMON FRESCO', 'PRODUCCION COCINA', 'Gr'),
('ITEM-e101e481', 'SALSA NEGRA', 'Insumos cocina', 'Ml'),
('ITEM-5d8f6750', 'SEAWEED SALAD', 'PRODUCCION COCINA', 'Gr'),
('ITEM-ac95c3e7', 'SODA', 'Producción BAR', 'Ml'),
('ITEM-02d4475a', 'SPAGHETTIS', 'Insumos cocina', 'Gr'),
('ITEM-a27c1dd2', 'SUNTEA', 'Producción BAR', 'Und'),
('ITEM-7794fc51', 'Sal', 'PRODUCCION COCINA', 'Gr'),
('ITEM-84fb3035', 'Salsa de soya', 'PRODUCCION COCINA', 'Ml'),
('ITEM-cfab948f', 'Salsa de tomate', 'Producción BAR', 'Und'),
('ITEM-a101bbc6', 'Salsa inglesa', 'Producción BAR', 'Und'),
('ITEM-607a7f32', 'Salsa picante chile', 'Producción BAR', 'Und'),
('ITEM-74f6c0ec', 'Salsa tabasco', 'Producción BAR', 'Und'),
('ITEM-c2ec2b0e', 'Singleton 12 años 700-ml', 'BOTELLAS', 'Und'),
('ITEM-23bde417', 'Soda Bretaña 300ml', 'BEBIDAS', 'Unidad'),
('ITEM-e79d8029', 'Soho Licor de Lichee 700ml', 'LICORES', 'Unidad'),
('ITEM-4379b251', 'Stevia', 'Producción BAR', 'Und'),
('ITEM-4435dc4f', 'Sucra ladiet', 'Producción BAR', 'Und'),
('ITEM-d5382f33', 'Suero Costeño', 'PRODUCCION COCINA', 'Gr'),
('ITEM-2476d71f', 'Syrup Simple', 'Producción BAR', 'Oz'),
('ITEM-152cd7ef', 'Syrup de gengibre', 'Producción BAR', 'Oz'),
('ITEM-2c658a0c', 'Syrup de romero', 'Producción BAR', 'Ml'),
('ITEM-23e53294', 'TAHINI', 'PRODUCCION COCINA', 'Gr'),
('ITEM-e5b62cd7', 'TOCINO CARNUDO', 'Insumos cocina', 'Gr'),
('ITEM-7cc2a3bc', 'TOMATE VERDE', 'PRODUCCION COCINA', 'Gr'),
('ITEM-801f1fa2', 'TOMILLO', 'Insumos cocina', 'Und'),
('ITEM-0b3ca6ce', 'TORTILLAS', 'Insumos cocina', 'Gr'),
('ITEM-75b003e3', 'Tabasco', 'ENTRADAS Y ENSALADAS', 'Gr'),
('ITEM-52d20f4c', 'Tabasco 65ml', 'Producción BAR', 'Und'),
('ITEM-f3773822', 'Tajin', 'Producción BAR', 'Und'),
('ITEM-3d434113', 'Te mansanilla', 'Producción BAR', 'Und'),
('ITEM-e8a95b6b', 'Te negro', 'Producción BAR', 'Und'),
('ITEM-f5d47dc8', 'Tequila 1800 Cristalino 700ml', 'TEQUILA / MEZCAL', 'Unidad'),
('ITEM-d60bc8e8', 'The Glenfiddich 12 - 750ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-8662a8eb', 'The Glenlivet 12  750-ml', 'BOTELLAS', 'Und'),
('ITEM-01b4149d', 'The Glenlivet 18 - 750ml', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-c2cbc1c5', 'The Glenlivet Founder', 'WHISKY / BOURBON', 'Unidad'),
('ITEM-9c8d78f7', 'Tocineta ahumada', 'Insumos cocina', 'Gr'),
('ITEM-02e409c8', 'Tomate', 'Insumos cocina', 'Gr'),
('ITEM-c103a3ae', 'Tomate Cherry', 'Insumos cocina', 'Gr'),
('ITEM-5dd7bf83', 'Torombolo', 'Producción BAR', 'Kg'),
('ITEM-46b1b318', 'Toronja deshidratada', 'Producción BAR', 'Und'),
('ITEM-d19414f5', 'Té miel y gengibre', 'Producción BAR', 'Und'),
('ITEM-fad004a8', 'Uchuva', 'Insumos cocina', 'Gr'),
('ITEM-f20db01f', 'Uva pasa', 'PRODUCCION COCINA', 'Gr'),
('ITEM-7e144c76', 'VINO BLANCO', 'PRODUCCION COCINA', 'Ml'),
('ITEM-c0a1728e', 'Vinagre 3000ML', 'Insumos cocina', 'Ml'),
('ITEM-b4051c4a', 'Vinagre balsamico', 'Insumos cocina', 'Ml'),
('ITEM-099cc507', 'Vino Blanco Rosaleda 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-168bba72', 'Vino Rosado Muga', 'VINOS / ESPUMOSOS', 'Und'),
('ITEM-339eae9d', 'Vino Rosaleda Rosse', 'VINOS / ESPUMOSOS', 'Und'),
('ITEM-3a2dc5d3', 'Vino Tinto 120 - 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-707d41e2', 'Vino Tinto La Celia 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-444e5a49', 'Vino Tinto Rosaleda 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-3a7550b0', 'Vino Tinto Santa Carolina Reservado 750ml', 'VINOS / ESPUMOSOS', 'Unidad'),
('ITEM-1e48046b', 'Vino Tinto Santa Helena', 'VINOS / ESPUMOSOS', 'Und'),
('ITEM-797b0c3b', 'Vodka Absolut 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-ffbb629e', 'Vodka Absolut Elix 750ml', 'VODKA / GIN', 'Unidad'),
('ITEM-d591e1d4', 'Vodka Grey Goose 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-045bb1ac', 'Vodka Smirnoff Red 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-3dbea024', 'Vodka Velvedere 700ml', 'VODKA / GIN', 'Unidad'),
('ITEM-694c4f7c', 'YOGUOR GRIEGO', 'Insumos cocina', 'Gr'),
('ITEM-5a6a7d7a', 'ZACAPA 23 750 ML', 'RON', 'Und'),
('ITEM-730a7491', 'ZARZAMORA', 'PRODUCCION COCINA', 'Gr'),
('ITEM-d89fe981', 'ZUQUINI AMARILLO', 'Insumos cocina', 'Gr'),
('ITEM-db180d32', 'ZUQUINI VERDE', 'Insumos cocina', 'Gr'),
('ITEM-9df39fdf', 'Zacapa Ambar 750ml', 'RON', 'Unidad'),
('ITEM-35be2606', 'Zanahoria', 'Insumos cocina', 'Gr'),
('ITEM-51ae9691', 'Zumo de corozo', 'Producción BAR', 'Ml'),
('ITEM-19589c6b', 'Zumo de lichee', 'Producción BAR', 'Ml'),
('ITEM-494405d4', 'Zumo de limon', 'Producción BAR', 'Ml'),
('ITEM-22993410', 'aguacate', 'Insumos cocina', 'Gr'),
('ITEM-1d0848bd', 'aguacate hass', 'Insumos cocina', 'Gr'),
('ITEM-64a5238e', 'ala de pollo', 'Insumos cocina', 'Kg'),
('ITEM-9a685cc1', 'arroz jazmin', 'Insumos cocina', 'Gr'),
('ITEM-d9cc913c', 'arroz parbolizado', 'Insumos cocina', 'Gr'),
('ITEM-19ab9ae4', 'blanqueador', 'Otros', 'Unidad'),
('ITEM-aec07f93', 'bola', 'Insumos cocina', 'Kg'),
('ITEM-b84679d2', 'bollito muchacho', 'Insumos cocina', 'Kg'),
('ITEM-007aa8ff', 'bolsas', 'Insumos cocina', 'Unidad'),
('ITEM-73c442ef', 'brownie', 'Insumos cocina', 'Und'),
('ITEM-951ca9df', 'butifarra', 'Insumos cocina', 'Und'),
('ITEM-46becd58', 'canela en polvo', 'Producción BAR', 'Und'),
('ITEM-88ea832a', 'cebollin', 'Insumos cocina', 'Gr'),
('ITEM-d5393f7a', 'chocolate corona', 'Insumos cocina', 'Gr'),
('ITEM-e7994d0f', 'chorizo antiqueño', 'Insumos cocina', 'Und'),
('ITEM-ac0ddf9e', 'coco', 'Insumos cocina', 'Und'),
('ITEM-02454813', 'cohete', 'Insumos cocina', 'Gr'),
('ITEM-4384dfc6', 'costillas san luis', 'Insumos cocina', 'Gr'),
('ITEM-80ac4139', 'curcuma', 'Insumos cocina', 'Gr'),
('ITEM-257e63c0', 'curry en polvo badia', 'Insumos cocina', 'Gr'),
('ITEM-e99f76dd', 'desayunos extras', 'Desayuno', 'Unidad'),
('ITEM-9f13c84b', 'desechables', 'COMPLEMENTOS Y ADICIONALES', 'Und'),
('ITEM-2ddba7ab', 'detergente', 'Otros', 'Unidad'),
('ITEM-33aff573', 'fideos', 'Insumos cocina', 'Gr'),
('ITEM-b3eb2955', 'flores comestibles', 'Insumos cocina', 'Und'),
('ITEM-fd829e28', 'frijoles negro', 'Insumos cocina', 'Gr'),
('ITEM-fea422ed', 'gelcomb', 'Otros', 'Unidad'),
('ITEM-7e9377ac', 'habichuelas', 'Insumos cocina', 'Gr'),
('ITEM-ad17497b', 'harina de choclo', 'Insumos cocina', 'Gr'),
('ITEM-8544e94d', 'harina de trigo', 'Insumos cocina', 'Gr'),
('ITEM-900847ab', 'jamon colanta', 'Insumos cocina', 'Gr'),
('ITEM-9d7547d6', 'jamon serrano', 'Insumos cocina', 'Gr'),
('ITEM-2e6961f1', 'laurel', 'Insumos cocina', 'Gr'),
('ITEM-eee5a88a', 'levadura', 'Insumos cocina', 'Gr'),
('ITEM-1d518d47', 'limpiador aro', 'Otros', 'Unidad'),
('ITEM-fde5a926', 'mango tommy', 'Insumos cocina', 'Gr'),
('ITEM-c015b8ff', 'manzanilla miel y jengibre', 'Producción BAR', 'Und'),
('ITEM-83907520', 'masa de chocosuela', 'Insumos cocina', 'Gr'),
('ITEM-6a25771a', 'maíz tierno', 'Insumos cocina', 'Gr'),
('ITEM-9cd630d9', 'mejillones', 'Insumos cocina', 'Gr'),
('ITEM-0f5ad346', 'mix de brotes', 'Insumos cocina', 'Gr'),
('ITEM-5f266b16', 'mix de lechugas', 'Insumos cocina', 'Gr'),
('ITEM-99bce3a5', 'morrillo', 'Insumos cocina', 'Kg'),
('ITEM-fb6a3d98', 'muslo de pollo', 'Insumos cocina', 'Kg'),
('ITEM-85158dc2', 'panko', 'Insumos cocina', 'Gr'),
('ITEM-2acd5a46', 'papas francesas', 'Insumos cocina', 'Gr'),
('ITEM-03a2f118', 'pasta de tomate', 'Insumos cocina', 'Gr'),
('ITEM-955578b2', 'pechuga de pollo', 'Insumos cocina', 'Kg'),
('ITEM-1459b3e5', 'peperoni', 'Insumos cocina', 'Gr'),
('ITEM-43264524', 'pepino europeo', 'Insumos cocina', 'Gr'),
('ITEM-d07eb893', 'perejil', 'Insumos cocina', 'Gr'),
('ITEM-d5d4135d', 'pimienta de olor', 'Insumos cocina', 'Gr'),
('ITEM-157ab37a', 'platanos', 'Insumos cocina', 'Und'),
('ITEM-85e998dd', 'platos de carton', 'Otros', 'Und'),
('ITEM-29d36bf5', 'polvo de hornear', 'Insumos cocina', 'Gr'),
('ITEM-2223461e', 'premezcla pancakes aunt jemima', 'Insumos cocina', 'Gr'),
('ITEM-6a7595fc', 'pulpa de guanabana', 'Producción BAR', 'Und'),
('ITEM-38c5ca2d', 'pulpa de maracuya', 'Producción BAR', 'Und'),
('ITEM-8452ee0d', 'quality blend', 'Producción BAR', 'Und'),
('ITEM-a82864c8', 'queso crema', 'Insumos cocina', 'Gr'),
('ITEM-2e8bb878', 'repollo morado', 'Insumos cocina', 'Gr'),
('ITEM-bbf6244a', 'robalo en posta', 'Insumos cocina', 'Kg'),
('ITEM-427dbb5e', 'sal gruesa', 'Insumos cocina', 'Gr'),
('ITEM-c29f0bcf', 'salchicha ahumada parisienne', 'Insumos cocina', 'Und'),
('ITEM-54346cd0', 'salchicha zenu long', 'Insumos cocina', 'Gr'),
('ITEM-e42b760a', 'sierra en posta', 'Insumos cocina', 'Und'),
('ITEM-e4df4280', 'sirope de jengibre', 'Producción BAR', 'Oz'),
('ITEM-5eafb022', 'suavizante aro', 'Otros', 'Unidad'),
('ITEM-0e3f191a', 'syrope Aunt jemima', 'Insumos cocina', 'Ml'),
('ITEM-35b02915', 'tomates en lata', 'Insumos cocina', 'Gr'),
('ITEM-d0757256', 'tortilla de maiz', 'Insumos cocina', 'Und'),
('ITEM-89d3fc9d', 'tortillas bimbo', 'Insumos cocina', 'Und'),
('ITEM-721264ee', 'tostadas susanita', 'Insumos cocina', 'Gr'),
('ITEM-66e40853', 'té negro premium', 'Producción BAR', 'Und'),
('ITEM-1947d751', 'té verde', 'Producción BAR', 'Und'),
('ITEM-0a1ee6f2', 'vasos desechables', 'Insumos cocina', 'Unidad'),
('ITEM-4a649ecc', 'yuca para personal', 'Insumos cocina', 'Kg'),
('ITEM-e8a205b1', 'zanahoria baby', 'Insumos cocina', 'Gr'),
('ITEM-4c5f689f', 'Ñame', 'PRODUCCION COCINA', 'Gr')
ON CONFLICT (id) DO UPDATE SET nombre = EXCLUDED.nombre, categoria = EXCLUDED.categoria, unidad = EXCLUDED.unidad;
